EquipmentRental/ViewModels/AddRentalDaysViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EquipmentRental.ViewModels
{
    public class AddRentalDaysViewModel
    {
        [Display(Name = "Rental days")]
        [Required(ErrorMessage = "Rental Days field is required")]
        [Range(1, 365, ErrorMessage = "Rental Days range should be between 1 and 365")]
        public int? RentalDays { get; set; }

        public string EquipmentId { get; set; }
    }
}

EquipmentRental/ViewModels/BasketViewModel.cs
using EquipmentRental.BusinessLogic.Interfaces;
using Unity;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using System.Threading.Tasks;
using EquipmentRental.BusinessLogic.Dtos;
using EquipmentRental.BusinessLogic.Enums;
using EquipmentRental.Models;

namespace EquipmentRental.ViewModels
{
    public class BasketViewModel
    {
        private readonly IEquipmentService _equipmentService;
        private readonly IRentalService _rentalService;
        private readonly IMapper _mapper;

        public BasketViewModel()
        {
            _mapper = UnityConfig.Container.Resolve<IMapper>();
            _rentalService = UnityConfig.Container.Resolve<IRentalService>();
            _equipmentService = UnityConfig.Container.Resolve<IEquipmentService>();
        }

        public async Task<BasketItem> AddAsync(string equipmentId, int rentalDays)
        {
            var equipmentDto = await _equipmentService.GetAsync(equipmentId);
            var equipment = _mapper.Map<EquipmentDto, Equipment>(equipmentDto);
            var basketItem = BasketItems.FirstOrDefault(x => x.Equipment.Id == equipmentId);

            if (basketItem == null)
            {
                basketItem = new BasketItem
                {
                    Equipment = equipment,
                    Quantity = 1,
                    RentalDays = rentalDays,
                    Price = _rentalService.GetPrice((EquipmentTypes)equipment.EquipmentType, rentalDays)
                };

                BasketItems.Add(basketItem);
            }
            else
            {
                basketItem.Quantity++;
            }

            return basketItem;
        }

        public decimal? Amount => BasketItems?.Sum(x => x.Price * x.Quantity);

        public int Count => BasketItems.Sum(x => x.Quantity);

        public List<BasketItem> BasketItems { get; set; } = new List<BasketItem>();
    }
}

EquipmentRental/Controllers/BasketController.cs
using AutoMapper;
using EquipmentRental.BusinessLogic.Dtos;
using EquipmentRental.BusinessLogic.Interfaces;
using EquipmentRental.Constants;
using EquipmentRental.Interfaces;
using EquipmentRental.ViewModels;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EquipmentRental.Controllers
{
    public class BasketController : Controller
    {
        private readonly BasketViewModel _basket;
        private readonly IMapper _mapper;
        private readonly ISessionFactory _sessionFactory;
        private readonly IRentalService _rentalService;

        public BasketController(IMapper mapper,
            ISessionFactory sessionFactory,
            IRentalService rentalService)
        {
            _mapper = mapper;
            _sessionFactory = sessionFactory;
            _rentalService = rentalService;
            _basket = sessionFactory.GetItem<BasketViewModel>("Basket");
        }

        public ActionResult AddRentalDays(string equipmentId)
        {
            if (string.IsNullOrEmpty(equipmentId))
            {
                throw new ArgumentNullException(nameof(equipmentId));
            }

            var model = new AddRentalDaysViewModel
            {
                EquipmentId = equipmentId
            };

            return PartialView("_AddRentalDays", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddRentalDays(AddRentalDaysViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_AddRentalDays", model);
            }

            await _basket.AddAsync(model.EquipmentId, model.RentalDays.GetValueOrDefault());

            return Json(new
            {
                isSuccess = true,
                redirectUrl = Url?.Action("Basket", "Basket")
            });
        }

        public async Task<ActionResult> Checkout()
        {
            var rentalDetails = _mapper.Map<List<BasketItem>, IEnumerable<RentalDetailDto>>(_basket.BasketItems);

            await _rentalService.CreateAsync(rentalDetails, FakeUserInfo.Email);

            _sessionFactory.Clear();

            return View("Confirmation");
        }

        public ActionResult Basket()
        {
            return PartialView("_Basket", _basket);
        }
    }
}

EquipmentRental/Controllers/RentalController.cs
using EquipmentRental.BusinessLogic.Interfaces;
using System.Web.Mvc;
using System.Net.Mime;
using EquipmentRental.Constants;
using System;
using System.Threading.Tasks;
using AutoMapper;
using System.Collections.Generic;
using EquipmentRental.BusinessLogic.Dtos;
using EquipmentRental.Models;

namespace EquipmentRental.Controllers
{
    public class RentalController : Controller
    {
        private readonly IRentalService _rentalService;
        private readonly IMapper _mapper;

        public RentalController(IMapper mapper, IRentalService rentalService)
        {
            _mapper = mapper;
            _rentalService = rentalService;
        }

        public async Task<ActionResult> Invoice()
        {
            var invoice = await _rentalService.GetInvoiceAsync(FakeUserInfo.Email);

            if (invoice == null)
            {
                throw new NullReferenceException(nameof(invoice));
            }

            return File(invoice, MediaTypeNames.Application.Octet, "Invoice.docx");
        }

        public async Task<ActionResult> Index()
        {
            var rentalsDto = await _rentalService.GetRentalsForUserAsync(FakeUserInfo.Email);
            var rentals = _mapper.Map<IEnumerable<RentalDto>, IEnumerable<Rental>>(rentalsDto);

            return View(rentals);
        }
    }
}

EquipmentRental/Views/Basket/Confirmation.cshtml
<div class="confirmation">
    <img class="mb-3" height="128" width="128" src="~/Content/Images/success.png" />
    <h2>Thank you for you order!</h2>
    <a class="btn btn-warning mt-4" href="@Url.Action("Index", "Rental")">Go To My Rentals</a>   
</div>

EquipmentRental/Views/Basket/_AddRentalDays.cshtml
@model EquipmentRental.ViewModels.AddRentalDaysViewModel

@using (Html.BeginForm("AddRentalDays", "Basket", FormMethod.Post, new { @class = "ajax-form", data_on_success = "equipmentrental.generic.callbacks.onSuccessAddRentalDays" }))
{
    @Html.HiddenFor(m => m.EquipmentId)
    @Html.AntiForgeryToken()

    <div id="modalBody" class="modal-body">
        <div class="form-group">
            @Html.LabelFor(m => m.RentalDays)
            @Html.TextBoxFor(m => m.RentalDays, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.RentalDays, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="modal-footer">
        <input type="submit" class="btn btn-primary" value="Add To Basket" />
    </div>
}

EquipmentRental/Views/Basket/_Basket.cshtml
@model EquipmentRental.ViewModels.BasketViewModel
@{
    var i = 0;
}
<div id="shopping-basket" data-basket-items-count="@Model.Count">
    <div class="modal-body">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Type</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Rental Days</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var basketItem in Model.BasketItems)
                {
                    <tr>
                        <th scope="row">@(++i)</th>
                        <td>@basketItem.Equipment.Name</td>
                        <td>@basketItem.Equipment.EquipmentType</td>
                        <td>@basketItem.Quantity</td>
                        <td>@basketItem.RentalDays</td>
                        <td>@(basketItem.Price * basketItem.Quantity)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="modal-footer">
        <a href="@Url.Action("Checkout", "Basket")" class="btn btn-primary">Checkout <i class="fas fa-chevron-double-right fa-lg"></i></a>
    </div>
</div>