EquipmentRental/Models/Rental.cs
using System;
using System.Collections.Generic;

namespace EquipmentRental.Models
{
    public class Rental : BaseModel
    {
        public DateTime StartDate { get; set; }

        public string UserId { get; set; }

        public virtual User User { get; set; }

        public virtual ICollection<RentalDetail> RentalDetails { get; set; } = new HashSet<RentalDetail>();
    }
}

EquipmentRental/Controllers/RentalController.cs
using EquipmentRental.BusinessLogic.Interfaces;
using System.Web.Mvc;
using System.Net.Mime;
using EquipmentRental.Constants;
using System;
using System.Threading.Tasks;
using AutoMapper;
using System.Collections.Generic;
using EquipmentRental.BusinessLogic.Dtos;
using EquipmentRental.Models;

namespace EquipmentRental.Controllers
{
    public class RentalController : Controller
    {
        private readonly IRentalService _rentalService;
        private readonly IMapper _mapper;

        public RentalController(IMapper mapper, IRentalService rentalService)
        {
            _mapper = mapper;
            _rentalService = rentalService;
        }

        public async Task<ActionResult> Invoice()
        {
            var invoice = await _rentalService.GetInvoiceAsync(FakeUserInfo.Email);

            if (invoice == null)
            {
                throw new NullReferenceException(nameof(invoice));
            }

            return File(invoice, MediaTypeNames.Application.Octet, "Invoice.docx");
        }

        public async Task<ActionResult> Index()
        {
            var rentalsDto = await _rentalService.GetRentalsForUserAsync(FakeUserInfo.Email);
            var rentals = _mapper.Map<IEnumerable<RentalDto>, IEnumerable<Rental>>(rentalsDto);

            return View(rentals);
        }
    }
}

EquipmentRental/Controllers/SharedController.cs
﻿using EquipmentRental.Interfaces;
using EquipmentRental.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace EquipmentRental.Controllers
{
    public class SharedController : Controller
    {
        private readonly ISessionFactory _sessionFactory;

        public SharedController(ISessionFactory sessionFactory)
        {
            _sessionFactory = sessionFactory;
        }

        public ActionResult Navigation(string selectedItem)
        {
            if (string.IsNullOrEmpty(selectedItem))
            {
                throw new ArgumentNullException(nameof(selectedItem));
            }

            var model = GetNavigationBarViewModel(selectedItem);

            return PartialView("_Navigation", model);
        }

        private NavigationBarViewModel GetNavigationBarViewModel(string selectedItem)
        {
            var menuItems = new List<MenuItem>
            {
                new MenuItem
                {
                    Value = "Equipments",
                    Text = "Equipments",
                    NavigateUrl = Url.Action("Index", "Equipment")
                },
                new MenuItem
                {
                    Value = "Rentals",
                    Text = "Rentals",
                    NavigateUrl = Url.Action("Index", "Rental")
                },
            };

            var selectedMenuItem = menuItems.FirstOrDefault(x => x.Text == selectedItem);

            if (selectedMenuItem != null)
            {
                selectedMenuItem.Selected = true;
            }

            var model = new NavigationBarViewModel
            {
                MenuItems = menuItems,
                BasketItemsCount = _sessionFactory.GetItem<BasketViewModel>("Basket").Count
            };

            return model;
        }
    }
}

EquipmentRental/Views/Rental/Index.cshtml
@model IEnumerable<EquipmentRental.Models.Rental>

@{
    ViewBag.Title = "Rentals";
    var i = 0;
}

@section navigation{
    @Html.Action("Navigation", "Shared", new { selectedItem = "Rentals" });
}

<div class="row">
    <div class="col-md-12">
        <a class="btn btn-success pull-right mb-4" href="@Url.Action("Invoice", "Rental")">Download Invoice <i class="fa fa-download" aria-hidden="true"></i></a>
    </div>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th>Image</th>
            <th>Name</th>
            <th>Type</th>
            <th>Date</th>
            <th>Rental Days</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rental in Model)
        {
            foreach (var rentalDetail in rental.RentalDetails)
            {
                <tr>
                    <th scope="row">@(++i)</th>
                    <td>
                        <img src="@rentalDetail.Equipment.ImgSource" alt="@rentalDetail.Equipment.Name" height="45" width="45" style="object-fit: contain" />
                    </td>
                    <td>@rentalDetail.Equipment.Name</td>
                    <td>@rentalDetail.Equipment.EquipmentType.ToString()</td>
                    <td>@rental.StartDate.ToString("dd-MM-yyyy")</td>
                    <td>@rentalDetail.RentalDays</td>
                </tr>
            }
        }
    </tbody>
</table>